name: Clean Folders

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # run nightly at 2:00 am

permissions:
  contents: write

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
    
      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"          

      - name: Build and Commit
        env:
          TOKEN: ${{ secrets.XDECAF_EDITOR_STAGING }}
        run: |
          node clean.js
          node buildIndex.js
          git config --global user.name 'DataFlowAnalysis'
          git config --global user.email 'DataFlowAnalysis@users.noreply.github.com'
          git commit -am "clean unused folders [skip ci]" || echo "No changes to commit"
          git push
